apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source
  namespace: edwin-dev-gitops
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce